### ISSUE TITLE
Diffing struct with private field *big.Int fails

### ISSUE THREAD

**Issue by raditzlawliet** [r3labs/diff#23]
I have problem when trying to diffing struct `decimal` from https://github.com/shopspring/decimal . looks like it fails because of private field `*big.Int`

Example code:

```go
package main

import (
	"fmt"
	"math/big"

	"github.com/r3labs/diff"
)

type number struct {
	value *big.Int
	exp   int32
}

func (n *number) SetValue(x int64) {
	n.value = big.NewInt(x)
}

func main() {
	a := number{}
	b := number{}
	b.SetValue(111)

	diffSliceOrder, _ := diff.NewDiffer(diff.SliceOrdering(true))
	changelog, err := diffSliceOrder.Diff(a, b)

	fmt.Println(err)
	fmt.Println(changelog)
}
```

we will get a panic

```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x525fc0, 0xc000046280, 0xb6, 0x1, 0x0, 0x0)
        c:/go/src/reflect/value.go:1014 +0x1c3
reflect.Value.Interface(...)
        c:/go/src/reflect/value.go:1003
github.com/r3labs/diff.(*Differ).diffPtr(0xc0000044e0, 0xc0000462b0, 0x1, 0x1, 0x525fc0, 0xc000046270, 0xb6, 0x525fc0, 0xc000046280, 0xb6, ...)
        E:/Go Project/pkg/mod/github.com/r3labs/diff@v0.0.0-20191120142937-b4ed99a31f5a/diff_pointer.go:33 +0x8b9
github.com/r3labs/diff.(*Differ).diff(0xc0000044e0, 0xc0000462b0, 0x1, 0x1, 0x525fc0, 0xc000046270, 0xb6, 0x525fc0, 0xc000046280, 0xb6, ...)
        E:/Go Project/pkg/mod/github.com/r3labs/diff@v0.0.0-20191120142937-b4ed99a31f5a/diff.go:128 +0x875
github.com/r3labs/diff.(*Differ).diffStruct(0xc0000044e0, 0x620358, 0x0, 0x0, 0x50bce0, 0xc000046270, 0x99, 0x50bce0, 0xc000046280, 0x99, ...)
        E:/Go Project/pkg/mod/github.com/r3labs/diff@v0.0.0-20191120142937-b4ed99a31f5a/diff_struct.go:50 +0x460
github.com/r3labs/diff.(*Differ).diff(0xc0000044e0, 0x620358, 0x0, 0x0, 0x50bce0, 0xc000046270, 0x99, 0x50bce0, 0xc000046280, 0x99, ...)
        E:/Go Project/pkg/mod/github.com/r3labs/diff@v0.0.0-20191120142937-b4ed99a31f5a/diff.go:112 +0xdf5
github.com/r3labs/diff.(*Differ).Diff(0xc0000044e0, 0x50bce0, 0xc000046270, 0x50bce0, 0xc000046280, 0x0, 0x461b54, 0x508c80, 0xc000046260, 0xc00008def0)
        E:/Go Project/pkg/mod/github.com/r3labs/diff@v0.0.0-20191120142937-b4ed99a31f5a/diff.go:101 +0x163
main.main()
        E:/Go Apps/raditzlawliet/xxx/xxx/experiment/differ.big.Int/main.go:25 +0x18a
exit status 2
```

**Comment by purehyperbole** [comment]
Thanks for reporting the issue. I'm currently looking at fixing the cause of the panic, but also adding support for `math/big` to the package which may take a little bit of time to implement correctly.

**Comment by ashishb** [comment]
It fails for a private *time.Location field as well.

**Comment by oiime** [comment]
Hello, I have a similar issue in time.Time, fails in `Time.loc.zone` through `func (st *sliceTracker) has(s, v reflect.Value)`
Perhaps it'll make sense to either add an option to ignore cases of private fields by defaulting to true, or add `if !x.CanInterface() { return fmt.Errorf("Unable to compare private fields of slice in %+v" ,path }` to `slice.has()` so it'll return an error instead of panicing

```
panic(0xdb7240, 0x132a400)
  	/opt/go/src/runtime/panic.go:969 +0x166
  reflect.valueInterface(0xe56f60, 0xc000584000, 0x1b9, 0x1, 0xe56f60,
     0xc000584000)
  	/opt/go/src/reflect/value.go:1011 +0x161
  reflect.Value.Interface(...)
  	/opt/go/src/reflect/value.go:1000
  github.com/r3labs/diff/v2.(*sliceTracker).has(0xc000592d48, 0xda90e0,
     0x1a9be90, 0x1b7, 0xe56f60, 0xc000584000, 0x1b9, 0xdabb40)
  	/home/ism/go/pkg/mod/github.com/r3labs/diff/v2@v2.6.0/diff_slice.go:103
     +0x11d
  github.com/r3labs/diff/v2.(*Differ).diffSliceGeneric(0xc00038ca80,
     0xc000577560, 0x3, 0x3, 0xda90e0, 0x1a9be90, 0x1b7, 0xda90e0, 0x1a9be90,
     0x1b7, ...)
  	/home/ism/go/pkg/mod/github.com/r3labs/diff/v2@v2.6.0/diff_slice.go:40
     +0x3fa
```
`

**Comment by ybzhanghx** [comment]
use  unsafe to fix this https://github.com/r3labs/diff/pull/43#issue-505934503
